global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'products'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['product-service:8091']
  - job_name: 'users'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['user-service:8092']
  - job_name: 'orders'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['order-service:8093']